baseURL: "https://diegosasso.github.io/"
title: Diego's Website
paginate: 5
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false


menu:
  main:
    - identifier: Publications
      name: Publications
      url: /Publications/
      weight: 1
    - identifier: Research
      name: Research
      url: /Research/
      weight: 2
    - identifier: Google Scholar
      name: Google Scholar
      url: "https://scholar.google.com/citations?user=hRTdDu4AAAAJ&hl"
      weight: 3
    - identifier: CV
      name: CV
      url: "CV_DiegoPorto_EN.pdf"
      weight: 4

params:
  defaultTheme: dark
  DateFormat: "January 2, 2006"
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true 


  title: DiegoWebsite
  description: "Diego's personal academic website"
  author: Diego S. Porto
  # images: ["<link or path of image for opengraph>"]


 # label:
 #   text: "Home"
 #   icon: /apple-touch-icon.png
 #   iconHeight: 35


  profileMode:
    enabled: true
    title: Diego S. Porto
    subtitle: "Hello, I am an Academy Research Fellow working at the Finnish Museum of Natural History in Helsinki, Finland. I am the leading investigator of the project “PhenoBees: a knowledgebase and integrative approach for studying the evolution of morphological traits in bees” funded by the Research Council of Finland ([Project](https://research.fi/en/results/funding/81159)).

I am a passionate evolutionary biologist specialized in the comparative morphology and systematics of bees. My research program is developed in the interface of morphology, phylogenetics, comparative methods, and computer science. My goal is to develop new tools to better understand the evolution of complex traits in bees and other organisms, particularly insects. I am also interested in developing new semantic data models to describe and integrate anatomical knowledge of insects using computational ontologies.

In my current research project, I am working to develop a semantic data workflow to integrate information from multiple sources (e.g., comparative datasets) and address hypotheses about the evolution of the mouthparts of bees. The research will produce a knowledgebase of phenotypic traits of bees ([PhenoBees](https://github.com/diegosasso/PhenoBees/wiki)) and new tools to analyze comparative semantic data.
"
    imageUrl: "/diego_img.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Diego_img
    #buttons:
    #  - name: something cool
    #    url: "https://xxx"
    #  - name: something cool
    #    url: "https://xxx"

  socialIcons:
    - name: email1
      url: "mailto:diego.sassoporto@helsinki.fi"
    - name: email2
      url: "mailto:diegosporto@gmail.com"      
    - name: twitter
      url: "https://twitter.com/PortoSasso"
    - name: mastodon
      url: "https://mastodon.social/@dsporto@ecoevo.social"
    - name: github
      url: "https://github.com/diegosasso"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
