baseURL: "https://diegosasso.github.io/"
title: Diego's Website
paginate: 5
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false


menu:
  main:
    - identifier: Publications
      name: Publications
      url: "publications_DiegoPorto.pdf"
      weight: 1
    - identifier: Research
      name: Research
      url: "research.md"
      weight: 2
    - identifier: Google Scholar
      name: Google Scholar
      url: "https://scholar.google.com/citations?user=hRTdDu4AAAAJ&hl"
      weight: 3
    - identifier: CV
      name: CV
      url: "CV_DiegoPorto_EN.pdf"
      weight: 4

params:
  defaultTheme: dark
  DateFormat: "January 2, 2006"
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true 


  title: DiegoWebsite
  description: "Diego's personal academic website"
  author: Diego S. Porto
  # images: ["<link or path of image for opengraph>"]


 # label:
 #   text: "Home"
 #   icon: /apple-touch-icon.png
 #   iconHeight: 35


  profileMode:
    enabled: true
    title: Diego S. Porto
    subtitle: "Hello, I am an Academy Research Fellow working at the Finnish Museum of Natural History in Helsinki, Finland. I am a passionate evolutionary biologist specialized in the comparative morphology and systematics of bees. My research program is developed in the interface of morphology, phylogenetics, comparative methods, and computer science. My goal is to develop new tools to better understand the evolution of complex traits in bees and other organisms, particularly insects. I am also interested in developing new semantic data models to describe and integrate anatomical knowledge of insects using computational ontologies."
    imageUrl: "/diego_img.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Diego_img
    #buttons:
    #  - name: something cool
    #    url: "https://xxx"
    #  - name: something cool
    #    url: "https://xxx"

  socialIcons:
    - name: email
      url: "mailto:diego.sassoporto@helsinki.fi"
    - name: email
      url: "mailto:diegosporto@gmail.com"      
    - name: twitter
      url: "https://twitter.com/PortoSasso"
    - name: mastodon
      url: "https://mastodon.social/@dsporto@ecoevo.social"
    - name: github
      url: "https://github.com/diegosasso"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
